export enum DEFAULTS {
  API_PORT = 3334,
  ADMIN_NAME = "admin",
  USERNAME = "Dogma user",
}

export enum GROUPS {
  BANNED = -1,
  GUEST = 0,
  USER = 1,
  MANAGER = 2,
  ADMIN = 3,
  OWNER = 4,
  TEST = 5,
}

export const ERRORS = {
  PAGE_NOT_FOUND: 900,
  USER_NOT_FOUND: 1000,
  PASSWORD_NOT_MATCH: 1001,
  USER_ALREADY_EXISTS: 1002,
  INVALID_CREDENTIALS: 1003,
  INVALID_LOGIN_CODE: 1004,
  INVALID_NODE_PREFIX: 1005,
  NOT_SIGNED: 1008,
};

export const CLIENT_STATUSES = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  ERROR: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
};

export const SERVER_STATUSES = {
  INTERNAL_ERROR: 500,
};
